#!/bin/sh
printf "\n\n 
=======================================
Developer: @stem grade
 
(YourTuber 4K 8K Video BY ♥️stem grade♥️)

            ❗️v1.0❗️

     🛑Made for Coco Tweaks🛑


🌐Get more cools Tweaks and hacks on the Coco Tweaks repo🌐
=======================================
\n\n"
