#!/bin/sh
printf "\n\n 
=======================================
Developer: @roarijo89
 
(In app purchase 2 BY ♥️roarijo89♥️)

            ❗️v0.0.1❗️

     🛑Made for Coco Tweaks🛑


🌐Get more cools Tweaks and hacks on the Coco Tweaks repo🌐
=======================================
\n\n"
