#!/bin/sh
printf "\n\n 
=======================================
Developer: @stem grade
 
(myiapcracker 2 BY ♥️stem grade♥️)

            ❗️v0.1.12❗️

     🛑Made for Coco Tweaks🛑


🌐Get more cools Tweaks and hacks on the Coco Tweaks repo🌐
=======================================
\n\n"
