#!/bin/sh
printf "\n\n 
=======================================
Owner : @roarijo89⚜️developer⚜️
 
Developer: @stem grade⚜️developer⚜️
 
(Tools 🛠 BY ♥️Coco Tweaks♥️)

            ❗️v1.4❗️

🌐Get more cools tweaks and hacks on my repo🌐
=======================================
\n\n"
