#!/bin/sh
printf "\n\n 
=======================================
Developer: @stem grade
 
(Cercube for youtube BY ♥️stem grade♥️)

            ❗️v5.2.3❗️

     🛑Made for Coco Tweaks🛑


🌐Get more cools Tweaks and hacks on the Coco Tweaks repo🌐
=======================================
\n\n"
