#!/bin/sh
printf "\n\n 
=======================================
Developer: @stem grade
 
(No revoke 2 BY ♥️stem grade♥️)

            ❗️v0.0.1❗️

      🛑Made for Coco Tweaks🛑


🌐Get more cools Tweaks and hacks on the Coco Tweaks repo🌐
=======================================
\n\n"
